# BiFlowNet model configuration.
# Usage: --model-config config/model/biflownet.yaml
model:
  class_name: BiFlowNet
  params:
    in_channels: 8
    out_channels: 8
    input_size: [32, 32, 32]
    dim: 72
    dim_mults: [1, 1, 2, 4, 8]
    sub_volume_size: [8, 8, 8]
    patch_size: 1
    attn_heads: 8
    init_dim: null
    init_kernel_size: 3
    use_sparse_linear_attn: [0, 0, 0, 1, 1]
    resnet_groups: 24
    dit_num_heads: 8
    mlp_ratio: 4.0
    num_mid_dit: 1
    cond_classes: null
    res_condition: true
    learn_sigma: false
