import_config: base.yaml

model:
  class_name: LocalDenoiser3D
  params:
    in_channels: 1
    out_channels: 1
    input_size: [32, 32, 32]
    patch_size: [2, 2, 2]
    hidden_size: 192
    depth: 1
    num_heads: 6
    mlp_ratio: 1.0
    tokenizer_kind: extract_patches
    tokenizer_patch_size: [4, 4, 4]
    tokenizer_stride: [2, 2, 2]
    tokenizer_padding: [1, 1, 1]
    swiglu_mlp: true
