model:
  class_name: PRDiT
  params:
    in_channels: 1
    out_channels: 2 # params of local denoiser
    input_size: [32, 32, 32]
    patch_size: [2, 2, 2]
    extract_patch_size: [4, 4, 4]
    extract_stride: [2, 2, 2]
    extract_padding: [1, 1, 1]
    hidden_size: 384

    depth: 0 # params of global residual DiT
    num_heads: 6
    mlp_ratio: 1.0
    coarse_mlp_ratio: 1.0
