import_config: voldit_dit_ds8_b2_whole_ds0125.yaml

stage1_model:
  params:
    load_from_ckpt: result/checkpoints/voldit_vqgan_lg00625.pth

model:
  params:
    input_size: [8, 64, 8]
    load_from_ckpt: /tmp/mlflow_checkpoints/voldit_whole_ds00625_ddp3_260617_094959_last.ckpt
