# VolDiT-L/2 for later formal training on zebrafish ds8 latents.
import_config: voldit_dit_ds8_xs2.yaml

model:
  params:
    patch_size: 2
    hidden_size: 1152
    depth: 24
    num_heads: 16
    load_from_ckpt: null
