# VolDiT stage-1 VQ-GAN model configuration.
# Usage: --model-config config/model/vqvae.yaml
import_config: voldit_vqgan_ds8.yaml

model:
  params:
    load_from_ckpt: result/checkpoints/voldit_vqgan_lg025_s1_20ep_best.pth
