seed: 42
resume_ckpt_path: null

logging:
  class_name: MLFlowLogger
  params:
    experiment_name: zebrafish_volume_gen
    run_name: base
    tracking_uri: http://172.27.2.100:5000
    tags:
      job_type: train
    log_model: false

trainer:
  class_name: Trainer
  params:
    max_epochs: 40
    accelerator: auto
    devices: 1
    precision: "bf16"
    deterministic: true
    check_val_every_n_epoch: 200
    enable_checkpointing: true
    gradient_clip_val: 1.0
    num_sanity_val_steps: 10 # WARNING: make sure first fusion is logs during validation before training
    accumulate_grad_batches: 1
    log_every_n_steps: 20
    logger: runtime.logging
    callbacks:
      - class_name: ModelCheckpoint
        params:
          monitor: val_loss
          mode: min
          save_top_k: 1
          save_last: true
          filename: "epoch{epoch:03d}-step{step:06d}"
          dirpath: runtime.artifact_manager.checkpoint_dir
      - class_name: IntegratedGPUMemoryMonitor
        params:
          log_frequency_mins: 1
      
      # To disable a callback, comment it out here and uncomment it when needed again.
      - class_name: EarlyStopping
        params:
          monitor: val_loss
          mode: min
          patience: 8
          min_delta: 1.0e-5
          strict: false
          check_finite: true
      - class_name: LearningRateMonitor
        params:
          logging_interval: epoch
