import_config: ddp7_prdit_s2_resume_gpu05_from_gpu07_lastv20_continue_bs8.yaml

trainer:
  params:
    devices: 2

logging:
  params:
    run_name: prdit_s2_ddp2_gpu67_gpu05_resume_from_gpu07_lastv20_continue_bs8
    tags:
      devices: "2"
