import_config: ddp4_recon_e20_early_stop.yaml

artifact_manager:
  class_name: ArtifactManager
  params:
    logger: runtime.logging
    staging_root: /data/volume3/share_storage/ym.xiao/dataresult/zebrafish/result/temp/runtime_temp

trainer:
  params:
    devices: 3
    max_epochs: 5000
    deterministic: false
    callbacks:
      - class_name: ModelCheckpoint
        params:
          monitor: val_recon_loss
          mode: min
          save_top_k: 1
          save_last: true
          filename: "epoch{epoch:03d}-step{step:06d}"
          dirpath: runtime.artifact_manager.checkpoint_dir
      - class_name: IntegratedGPUMemoryMonitor
        params:
          log_frequency_mins: 1
      - class_name: LearningRateMonitor
        params:
          logging_interval: epoch
