import_config: base.yaml

artifact_manager:
  class_name: ArtifactManager
  params:
    logger: runtime.logging
    staging_root: /data/volume3/share_storage/ym.xiao/dataresult/zebrafish/result/temp/runtime_temp

resume_ckpt_path: null

train_dataloader:
  params:
    batch_size: 512

val_dataloader:
  params:
    batch_size: 512

trainer:
  params:
    devices: 4
    strategy: ddp_find_unused_parameters_true
    precision: "bf16-mixed"
    max_epochs: 20000
    check_val_every_n_epoch: 200
