import_config:
  - ddp4_voldit_finetune.yaml
  - _callbacks_val_loss_no_early_stopping.yaml

resume_ckpt_path: null

trainer:
  params:
    max_epochs: 100

logging:
  params:
    tags:
      init: voldit_whole_ds00625_last_260617_094959
      data_geometry: whole_crop_ds0125_or_ds00625
      launch_profile: ddp4_gpu07
