import_config:
  - base.yaml
  - _callbacks_val_recon_loss_no_early_stopping.yaml

trainer:
  params:
    devices: 4
    strategy: ddp_find_unused_parameters_false
    precision: "bf16-true"
    num_sanity_val_steps: 0
    log_every_n_steps: 1
