import_config: ddp4_voldit_finetune.yaml

trainer:
  params:
    max_epochs: 60

logging:
  params:
    tags:
      init: load_from_ckpt_epoch032_step002739
      training_fix: latent_ddpm_raw_timesteps
