# 4-GPU DDP wrapper for VQ-VAE stage 1.
import_config:
  - base.yaml
  - _callbacks_val_recon_loss_no_early_stopping.yaml

trainer:
  params:
    max_epochs: 20
    devices: 4
    strategy: ddp_find_unused_parameters_true
    gradient_clip_val: 0.0
    precision: "bf16-mixed"
