import_config:
  - base.yaml
  - _callbacks_val_loss_no_early_stopping.yaml

trainer:
  params:
    devices: 4
    strategy: ddp_find_unused_parameters_false
    precision: "bf16-mixed"
    num_sanity_val_steps: 0
    log_every_n_steps: 1

logging:
  params:
    experiment_name: trellis_finetune
    tags:
      pipeline: trellis_ss_flow_occupancy
      launch_profile: ddp4_gpu07
