import_config: ddp4_prdit_s2.yaml

trainer:
  params:
    devices: 6

logging:
  params:
    run_name: prdit_s2_ddp6_gpu05_smbatch
    tags:
      node: gpu05
      data_config: lg_025_smbatch
      devices: "6"
