import_config:
  - ddp6_prdit_s2.yaml
  - _callbacks_val_loss_no_early_stopping.yaml

resume_ckpt_path: /tmp/mlflow_checkpoints/prdit_s2_ddp4_resume_gpu07_260609_150700_last-v20.ckpt

trainer:
  params:
    max_epochs: 100

logging:
  params:
    run_name: prdit_s2_ddp6_gpu05_resume_from_gpu07_lastv20_bs8_continue
    tags:
      data_config: lg_025_network_file_bs8
      resume: gpu07_last_v20_local_tmp
