import_config: ddp7_prdit_s1_gpu05_network_file.yaml

resume_ckpt_path: /tmp/prdit_s1_260608_064826_last.ckpt

trainer:
  params:
    check_val_every_n_epoch: 1

logging:
  params:
    run_name: prdit_s1_ddp7_gpu05_network_file_resume
    tags:
      resume: last_ckpt_260608_064826
