import_config:
  - ddp7_prdit_s2.yaml
  - _callbacks_val_loss_no_early_stopping.yaml

resume_ckpt_path: /tmp/mlflow_checkpoints/prdit_s2_ddp4_resume_gpu07_260609_150700_last-v20.ckpt

trainer:
  params:
    max_epochs: 100

logging:
  params:
    run_name: prdit_s2_ddp7_gpu05_resume_from_gpu07_lastv20_continue
    tags:
      resume: gpu07_last_v20_local_tmp_to_epoch100
