import_config: ddp4_prdit_s1.yaml

trainer:
  params:
    devices: 7
    check_val_every_n_epoch: 5

logging:
  params:
    run_name: prdit_s1_ddp7_gpu05_network_file
    tags:
      stage: "1"
      node: gpu05
      data_config: lg_025_network_file
      devices: "7"
