import_config: base.yaml

train_dataloader:
  params:
    batch_size: 1
    num_workers: 0
    prefetch_factor: null
    persistent_workers: false
    drop_last: true

val_dataloader:
  params:
    batch_size: 1
    num_workers: 0
    prefetch_factor: null
    persistent_workers: false
    drop_last: false

trainer:
  params:
    devices: 8
    strategy: ddp_find_unused_parameters_false
    precision: "bf16-mixed"
    max_epochs: 5
    deterministic: false
    log_every_n_steps: 1
    enable_progress_bar: false
    check_val_every_n_epoch: 100
    enable_checkpointing: false
    num_sanity_val_steps: -1
    callbacks:
      - class_name: IntegratedGPUMemoryMonitor
        params:
          log_frequency_mins: 0.01
