import_config: base.yaml

logging:
  params:
    experiment_name: local_denoier
    tags:
      job_type: batch_probe
      backbone: local_denoiser
      dataset_kind: patch
      scale: "0.125"
      dataset: LS-FIS-3dpf
    gpu_memory_monitor:
      enabled: false

trainer:
  params:
    max_epochs: 1
    accelerator: gpu
    devices: 1
    precision: "16-mixed"
    log_every_n_steps: 1
    enable_checkpointing: false
    num_sanity_val_steps: 0
    limit_val_batches: 0.0
    callbacks:
      - class_name: ModelCheckpoint
        params:
          save_top_k: 0
          save_last: false
          dirpath: runtime.artifact_manager.checkpoint_dir
      - class_name: EarlyStopping
        params:
          enabled: false
      - class_name: LearningRateMonitor
        params:
          logging_interval: epoch

testing:
  run_sampling_after_fit: false
  num_samples: 1
  sample_steps: 4
