import_config: base.yaml

trainer:
  params:
    max_epochs: 10
    accelerator: gpu
    devices: 1

logging:
  params:
    experiment_name: prdit_s2_IaN
    run_name: prdit_s2
    tags:
      stage: "2"
