import_config: prdit_s1.yaml

resume_ckpt_path: null

trainer:
  params:
    max_epochs: 0
    devices: 1
    limit_val_batches: 0.1 # only for num_sanity_val_steps pre validate to see fusion result

logging:
  params:
    run_name: test
    tags:
      job_type: test
