framework:
  class_name: IaNFlowModule
  params:
    model: runtime.model
    stage: 2
    optimization:
      learning_rate: 0.00002  # 2e-5
      weight_decay: 0.0
      loss_type: mse
      sample_steps: 250
    diffusion:
      timestep_respacing: null
