framework:
  class_name: IaNFlowModule
  params:
    model: runtime.model
    stage: 1
    optimization:
      learning_rate: 0.0001
      weight_decay: 0.0
      loss_type: mse
      sample_steps: 50
    diffusion:
      timestep_respacing: null
