framework:
  class_name: VICRegModule
  params:
    model: runtime.model
    sim_weight: 25.0
    var_weight: 25.0
    cov_weight: 5.0
    lr: 0.00001 # Finetune on medical net, use very small learning rate
    weight_decay: 0.000001

logging:
  params:
    run_name: vic_reg_run